name: Windows - Core

on:
  release:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-core-windows:
    runs-on: windows-2019

    env:
      GIT_COMMIT: ${{ github.sha }}
      BONJOUR_BASE_DIR: ${{ github.workspace }}\deps\bonjour
      SYNERGY_NO_LEGACY: "1"
      SYNERGY_NO_TESTS: "1"
      SYNERGY_STATIC_OPENSSL: "1"

    steps:
      - uses: actions/checkout@v2

      - name: Cache Bonjour
        id: cache-bonjour
        uses: actions/cache@v1
        with:
          path: ${{ env.BONJOUR_BASE_DIR }}
          key: ${{ runner.os }}-Bonjour

      - name: Install Bonjour SDK
        if: steps.cache-bonjour.outputs.cache-hit != 'true'
        run: |
          New-Item -Force -ItemType Directory -Path "$env:BONJOUR_BASE_DIR"
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://binaries.symless.com/bonjour/BonjourSDK.zip",".\bonjoursdk.zip")
          [System.IO.Compression.ZipFile]::ExtractToDirectory(".\bonjoursdk.zip", "$env:BONJOUR_BASE_DIR")

      - name: Install OpenSSL
        run: |
          choco uninstall openssl -y --ignore-autouninstaller-failure --no-progress
          choco install openssl -y --no-progress

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        env:
          CMAKE_PREFIX_PATH: "C:\\Program Files\\OpenSSL-Win64"
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          msbuild synergy-core.sln `
            /p:Platform="x64" `
            /p:Configuration=Release `
            /m

      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/bin/Release/*
